### ISSUE TITLE
Works Only with Standard Power BI Desktop

### ISSUE THREAD

**Issue by EminUZUN** [didierterrien/Power-BI-assistant#1]
Hello, It works only with standart power bi desktop
I have rearranged it to work with Power BI SSRS and Power BI Desktop Storeapp
[https://1drv.ms/u/s!AoH-J1S5R_pd5SCrEnGnjovnRp6Q](url)

**Comment by didierterrien** [comment]
Hello Emin,
Yes I noticed it didn't work with Windows store version but I couldn't fix it yet so thank you very much to provide this new version. Formulas search is the first part of a bigger project so I need to modify the whole project. Would you please tell me :- where you modified the pbix file ? Which queries ?- how it works with SSRS ? Do you mean you published the report to SSRS and SSRS gets access to the local instance of SSAS ? What are the advantages to do that ?When I will know how to update my Power BI report, I will give credits to you. If you want me to add a link please give it to me (may be your LinkedIn profile?)Best regards Didier
Didier Terrien

-------- Message d'origine --------
De : EminUZUN <notifications@github.com> 
Date : 19/03/2018  19:53  (GMT+01:00) 
À : didierterrien/Power-BI-assistant <Power-BI-assistant@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com> 
Objet : [didierterrien/Power-BI-assistant] Works Only with Standard Power BI
&nbsp; Desktop (#1) 

Hello, It works only with standart power bi desktop

I have rearranged it to work with Power BI SSRS and Power BI Desktop Storeapp

https://1drv.ms/u/s!AoH-J1S5R_pd5SCrEnGnjovnRp6Q

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/didierterrien/Power-BI-assistant","title":"didierterrien/Power-BI-assistant","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/didierterrien/Power-BI-assistant"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Works Only with Standard Power BI Desktop (#1)"}],"action":{"name":"View Issue","url":"https://github.com/didierterrien/Power-BI-assistant/issues/1"}}}

**Comment by EminUZUN** [comment]
I've created new table named "FolderFiles" and appended all locations needed for all 3 desktop versions of Power BI. (I didnt mean to retrieve data from SSRS or SSAS itself. I was meaning Power BI Desktop RS Server version).
After creating appended FolderFiles, I've changed all functions which was addressing a folder
I have modified MSMDSRVport, MSMDSRVports, Memory etc. (Any query that uses port).

FolderFiles lists files from these directories:
C:\Users\CurrentUser\Microsoft\Power BI Desktop Store App\AnalysisServicesWorkspaces
C:\Users\CurrentUser\AppData\Local\Microsoft\Power BI Desktop\AnalysisServicesWorkspaces
C:\Users\CurrentUser\AppData\Local\Microsoft\Power BI Desktop SSRS\AnalysisServicesWorkspaces

Meanwhile, it is possible to connect to SSAS, you may check these links: https://datasavvy.me/2017/09/19/the-tabular-model-documenter-is-now-a-power-bi-template/
https://www.blue-granite.com/blog/demo-day-document-your-tabular-model-with-excel-or-power-bi

Complete template can be found in this link:
Power BI file - Tabular Model Documentor Template
https://www.blue-granite.com/hubfs/Docs/Tabular_Model_Documentation.zip
Excel file - Tabular Model Documentor Template
https://www.blue-granite.com/hubfs/Docs/Tabular_PBI_Documentation.zip

And I just came across this link: 
https://prathy.com/2017/12/power-bi-template-to-document-the-power-bi-service/

Regards,

P.S. You have me in your linkedin contacts :)

**Comment by didierterrien** [comment]
Hello Emin,
Wow, the last link you sent to me is wonderfull !!!
I added some of your links to Power BI assistant
Thank you
