### ISSUE TITLE
Cannot Load PBIX Files to PBI Assistant

### ISSUE THREAD

**Issue by mhammons** [didierterrien/Power-BI-assistant#2]
Hello, I cannot get any of the pbix files to load in pbi-assistant. 

I am using v2-2. I updated the file to my windows username. I have 1 other pbix file open. When I try to refresh, I get this error on the PBI Report  ID table - "We cannot convert the value false to type Table" and all other tables - "Load was canceled by an error in loading a previous table".﻿

I tried other pbix files as well.

Any suggestions?

**Comment by didierterrien** [comment]
Hello,
Thank you to report this issue.It seems the problem appears during the refresh so I suppose it comes from the M code.Could you please give this information :   Which version of power bi do you use?   Is it the version downloaded from the web site or from the windows store or is it the version for report server?   Could you please send a screenshot of the refresh white screen. One line give the error and other lines state is "Load was canceled by an error in loading a previous table". Only the error line is relevant.   Could you please send a sample pbix file to help me to reproduce the problem?Best regardsDidier Terrien

-------- Message d'origine --------
De : mhammons <notifications@github.com> 
Date : 20/07/2018  15:51  (GMT+01:00) 
À : didierterrien/Power-BI-assistant <Power-BI-assistant@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com> 
Objet : [didierterrien/Power-BI-assistant] Cannot Load PBIX Files to PBI
&nbsp; Assistant (#2) 

Hello, I cannot get any of the pbix files to load in pbi-assistant.
I am using v2-2. I updated the file to my windows username. I have 1 other pbix file open. When I try to refresh, I get this error on the PBI Report  ID table - "We cannot convert the value false to type Table" and all other tables - "Load was canceled by an error in loading a previous table".﻿
I tried other pbix files as well.
Any suggestions?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/didierterrien/Power-BI-assistant","title":"didierterrien/Power-BI-assistant","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/didierterrien/Power-BI-assistant"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Cannot Load PBIX Files to PBI Assistant (#2)"}],"action":{"name":"View Issue","url":"https://github.com/didierterrien/Power-BI-assistant/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/didierterrien/Power-BI-assistant/issues/2",
"url": "https://github.com/didierterrien/Power-BI-assistant/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Cannot Load PBIX Files to PBI Assistant (#2)",
"sections": [
{
"text": "",
"activityTitle": "**mhammons**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mhammons",
"facts": [
{
"name": "Repository: ",
"value": "didierterrien/Power-BI-assistant"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"didierterrien/Power-BI-assistant\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"didierterrien/Power-BI-assistant\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/didierterrien/Power-BI-assistant/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 358630970\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mhammons** [comment]
Hello,
Power BI - v2.60.5169.3201 64-bit (July 2019) - download from website

The screenshot and pbix file are attached.
![pbiassistant-error](https://user-images.githubusercontent.com/36681041/43163990-e86e6e22-8f5d-11e8-9f8e-81bd97aa3025.png)
[dynad-media.zip](https://github.com/didierterrien/Power-BI-assistant/files/2225263/dynad-media.zip)

Mike

**Comment by didierterrien** [comment]
Hello,

Thank you for providing information. 
We have both the same version downloaded from the website but it works for me with your report:
![image](https://user-images.githubusercontent.com/37301981/43197064-4d57c3ea-900a-11e8-8b3e-9f7665d0dcf3.png)

Please compare the windows user name you typed with your C:\Users subfolders:
![image](https://user-images.githubusercontent.com/37301981/43197212-c54bae98-900a-11e8-933d-04ad4f660a09.png)
![image](https://user-images.githubusercontent.com/37301981/43197388-52c270c2-900b-11e8-8b3e-1d4300b52870.png)

You can also go to power query and check each step in "PBI reports ID" query (except "AddedTable" step). You may post screenshots with errors
![image](https://user-images.githubusercontent.com/37301981/43198317-8a916c3a-900e-11e8-82a4-5464d1138656.png)

Thank you again to help to improve the tool and sorry for the inconvenience
Didier
